#!/usr/bin/env bash

# SSH into server using the private key from the new location with user ubuntu
ssh-keygen -b 4096 -f /alu-system_engineering-devops/.ssh/school -t rsa -N betty

# Exit after connecting (this line will execute after the SSH session ends)
echo "Connection to 8.8.8.8 closed."

