#!/usr/bin/env bash 

# Generate a 4096-bit RSA key pair and save it to /root/.ssh/school
ssh-keygen -b 4096 -f ~/.ssh/school -t rsa -N betty

# Ensure correct permissions for the private key
chmod 600 ~/.ssh/school

