#!/usr/bin/env bash
# Script to install and configure HAProxy as a load balancer.

# Update package list and install HAProxy
sudo apt update -y
sudo apt install haproxy -y

# Enable HAProxy to start on boot
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
haproxy_config="global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6074-web-01 44.220.131.227:80 check
    server 6074-web-02 50.19.26.220:80 check
"

# Write HAProxy configuration
echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
