#!/usr/bin/env bash

# Update and upgrade the package lists
sudo apt-get update && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Create the index.html file with the required content
echo "Holberton School" | sudo tee /var/www/html/index.html

# Restart Nginx to apply the changes
sudo service nginx restart

