#!/usr/bin/env bash
# Script to install Nginx, configure a custom 404 page

# Update package list and install Nginx
sudo apt update -y
sudo apt install nginx -y

# Ensure the correct document root directory exists
sudo mkdir -p /var/www/html

# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Store configuration content
new_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
"

# Write configuration to Nginx
echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Test Nginx configuration for errors
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
